[versions]
kotlin = "1.9.23"
dokka = "1.9.20"
shadow = "8.1.1"
paper = "1.20.6-R0.1-SNAPSHOT"

[libraries]
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }